### ISSUE TITLE
No longer working after newly installed MS Patches

### ISSUE THREAD

**Issue by ServerJock** [AsteriskAmpersand/MHW-Save-Editor#26]
Hello,

I patched my PC and it the application now just crashes when I attempt to save. Below are the logs from eventvwr.

Fault bucket 1415180334857844996, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: MHW Save Editor.exe
P2: 1.0.0.0
P3: b91299f4
P4: mscorlib
P5: 4.7.3362.0
P6: 5c2fce36
P7: 1688
P8: fd
P9: System.IO.DirectoryNotFound
P10: 
----------------------------------------------------------------
Faulting application name: MHW Save Editor.exe, version: 1.0.0.0, time stamp: 0xb91299f4
Faulting module name: KERNELBASE.dll, version: 10.0.17763.404, time stamp: 0x2528b630
Exception code: 0xe0434352
Fault offset: 0x0000000000039129
Faulting process id: 0x166c
Faulting application start time: 0x01d4f1f225e05f10
Faulting application path: C:\Users\User\Desktop\MHW\MHW Save Editor.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 1c6757d1-5477-433a-a552-7c41a5bdc1a2
Faulting package full name: 
Faulting package-relative application ID: 
----------------------------------------------------------------
Application: MHW Save Editor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileSystemEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CommonInit()
   at System.IO.FileSystemEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.String, System.String, System.String, System.IO.SearchOption, System.IO.SearchResultHandler`1<System.__Canon>, Boolean)
   at System.IO.Directory.GetDirectories(System.String)
   at MHW_Save_Editor.Utility.getSteamPath()
   at MHW_Save_Editor.MainWindow.SaveFunction(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at MHW.App.Main()
   at MHW.Program.Main()

**Comment by ServerJock** [comment]
I was able to resolve the problem by reinstalling Steam. Not sure what happened but it is working now. You can close this ticket. Thanks for all of your hard work.
